### ISSUE TITLE
Questions about the sparse depth injector:

### ISSUE THREAD

**Issue by ReRadioActivity** [KU-CVLAB/3DFuse#10]
1. Is ANY 3d data required for the training of sparse depth injector? I think the paper says that it doesn't, but I just want to be sure.
2. Is code for training the sparse depth injector available in your repo? If yes, then can you tell me in what directory?
3. How much time and computational power does it require to train it?
Thanks in advance. Hope, that the questions are not getting too bothersome.

**Comment by j0seo** [comment]
Hi, @ReRadioActivity  Thank you for your interest in our work! First, please note that we used the Co3D(v2) dataset for point clouds as mentioned in the paper. Although the train code is not yet available in this repository, the sparse depth injector follows the structure of ControlNet, so you can use the train code from the official ControlNet repository at first. (We are preparing an appendix with specific training details.) For training, it took us 3-4 days with 8 NVIDIA RTX3090s.
