### ISSUE TITLE
3D model

### ISSUE THREAD

**Issue by Wangcongyu620** [KU-CVLAB/3DFuse#14]
Thank you for providing such a great job. May I ask if it is possible to save the 3D model to result? For example, obj, what should I do?

**Comment by j0seo** [comment]
Hi @Wangcongyu620, if the output you are referring to is a mesh, additional post-processing is required. I am organizing the code for this. Alternatively, you can use[ another converting code](https://github.com/cvlab-columbia/zero123/issues/36) that is also based on SJC like our work.
