### ISSUE TITLE
hugging face demo

### ISSUE THREAD

**Issue by scatterp2** [KU-CVLAB/3DFuse#15]
it fails just says error

**Comment by j0seo** [comment]
Hi, thank you for letting me know. I found an error in unknown situations, and after that, all subsequent requests exceed the GPU memory usage. I'll let you know as soon as it is resolved.

**Comment by scatterp2** [comment]
thanks for the update looking forward to hearing more

**Comment by j0seo** [comment]
I checked and it seems that there was a temporary error due to heavy traffic, now fixed. But, unfortunately, Huggingface's GPU grant has expired, so you will need to duplicate it to your own space to use. Thanks!
