### ISSUE TITLE
Why green background

### ISSUE THREAD

**Issue by Adamdad** [KU-CVLAB/3DFuse#17]
Firstly, I would like to express my gratitude for your excellent work. 

However, I have noticed that when I run the code, the resulting nerf model consistently appears with a green background color, and I am unsure about the reason behind this. I would like to inquire if you have any insights or suggestions regarding this issue. 

It's worth mentioning that I haven't observed this phenomenon with other methods such as SJC and Dreambooth. I would appreciate any help you can provide in resolving this matter. 

Thank you.

**Comment by j0seo** [comment]
Thanks for your interest in our work! Our work is based on voxel-based radiance fields in a latent space, the same as SJC. In our setting, [blend_bg_texture](https://github.com/KU-CVLAB/3DFuse/blob/cc1a26e81473d638a31142d5c24278eb0a42d93a/run_3DFuse.py#L57) is set to False by default. If you change it to True, you can see a textured background shown in SJC.
Our work is designed for generating objects by utilizing the emptiness loss mentioned in SJC. As a result, the background is not reconstructed together, and we set the default color to green. To change this, you can check [this part](https://github.com/KU-CVLAB/3DFuse/blob/cc1a26e81473d638a31142d5c24278eb0a42d93a/voxnerf/render.py#L200) (although it is not easy to adjust for desired color accurately as it is rendered in the latent space). If you have any more questions, please feel free to ask!
