### ISSUE TITLE
bad case 

### ISSUE THREAD

**Issue by No360201** [KU-CVLAB/3DFuse#21]
when i set prompt is " cute small corgi" and "a ladybug",why the result is this

https://user-images.githubusercontent.com/57511687/236725037-a2da8675-a8cd-496a-a22f-e40e7173c2a4.mp4

https://user-images.githubusercontent.com/57511687/236725063-f2c46181-5fae-4b3d-aa12-05942700c7b5.mp4

i changed semantic_coding.py (image[~mask] = [255., 255., 255.])  to
`image[~mask[:,:,3]] = [255., 255., 255.]`.

**Comment by j0seo** [comment]
Hello, it appears that there has been error propagation of Point-E during the point cloud inference process. Although this framework can address some errors in point clouds, it struggles with point clouds that are completely geometrically incorrect in inference, and we leaved this as future work. Please refer to #11 for more information on this matter.

**Comment by No360201** [comment]
> Hello, it appears that there has been error propagation of Point-E during the point cloud inference process. Although this framework can address some errors in point clouds, it struggles with point clouds that are completely geometrically incorrect in inference, and we leaved this as future work. Please refer to #11 for more information on this matter.

you mean if we provide better point cloud ,we can get a right result

**Comment by j0seo** [comment]
Yes, generally, there is a tendency toward that.
