### ISSUE TITLE
Program termination on colab

### ISSUE THREAD

**Issue by litaiqing1** [KU-CVLAB/3DFuse#25]
I'm running the code on a Google colab with a graphics card T4 (15GB), but it produces the following output, the program stops and no error is reported.In the last line, what is the reason for "killed" and how can I fix it?：

Collapsing Lin Lora in 0
Collapsing Lin Lora in proj
Collapsing Lin Lora in k_proj
Collapsing Lin Lora in v_proj
Collapsing Lin Lora in q_proj
Collapsing Lin Lora in out_proj
Collapsing Lin Lora in k_proj
Collapsing Lin Lora in v_proj
Collapsing Lin Lora in q_proj
Collapsing Lin Lora in out_proj
Collapsing Lin Lora in k_proj
Collapsing Lin Lora in v_proj
Collapsing Lin Lora in q_proj
Collapsing Lin Lora in out_proj
Collapsing Lin Lora in k_proj
Collapsing Lin Lora in v_proj
Collapsing Lin Lora in q_proj
Collapsing Lin Lora in out_proj
Collapsing Lin Lora in k_proj
Collapsing Lin Lora in v_proj
Collapsing Lin Lora in q_proj
Collapsing Lin Lora in out_proj
Collapsing Lin Lora in k_proj
Collapsing Lin Lora in v_proj
Collapsing Lin Lora in q_proj
Collapsing Lin Lora in out_proj
Collapsing Lin Lora in k_proj
Collapsing Lin Lora in v_proj
Collapsing Lin Lora in q_proj
Collapsing Lin Lora in out_proj
Collapsing Lin Lora in k_proj
Collapsing Lin Lora in v_proj
Collapsing Lin Lora in q_proj
Collapsing Lin Lora in out_proj
Collapsing Lin Lora in k_proj
Collapsing Lin Lora in v_proj
Collapsing Lin Lora in q_proj
Collapsing Lin Lora in out_proj
Collapsing Lin Lora in k_proj
Collapsing Lin Lora in v_proj
Collapsing Lin Lora in q_proj
Collapsing Lin Lora in out_proj
Collapsing Lin Lora in k_proj
Collapsing Lin Lora in v_proj
Collapsing Lin Lora in q_proj
Collapsing Lin Lora in out_proj
Collapsing Lin Lora in k_proj
Collapsing Lin Lora in v_proj
Collapsing Lin Lora in q_proj
Collapsing Lin Lora in out_proj
Killed

**Comment by prateekgulati** [comment]
Did you resolve this? I am facing a similar error
