### ISSUE TITLE
Hello. Nice repo. I have three questions:

### ISSUE THREAD

**Issue by ReRadioActivity** [KU-CVLAB/3DFuse#3]
1. How much VRAM do you need to run this locally?
2. When will the Colab and HuggingFace demos be available?
3. When will the point cloud to mesh converter be ready? Are you going to use Open3D library?

**Comment by j0seo** [comment]
1. Approximately 18GB of VRAM is required. We proceeded with a single RTX 3090.
2. We expect to release the demo within a week if there are no major issues.
3. It is difficult to estimate as we have not started yet. We will update the progress here if there is any update!

**Comment by ReRadioActivity** [comment]
Is it possible to use any other custom SD-based model and get a decent result? Or only the ones that are presented in the Gradio demo work properly?
