### ISSUE TITLE
installing pytorch3d on windows is a pain in the ssa, is there any alternative?

### ISSUE THREAD

**Issue by destlaver** [KU-CVLAB/3DFuse#4]

**Comment by j0seo** [comment]
Have you tried to install from GitHub?
pip install git+https://github.com/facebookresearch/pytorch3d@c8af1c45ca9f4fdd4e59b49172ca74983ff3147a#egg=pytorch3d

Or, it seems the installation method for Windows is provided at https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md.

Additionally, we also sometimes had difficulties installing PyTorch3D in some environments, so we are considering releasing a version that includes some of the code used in PyTorch3D, which does not need to install Pytorch3D.

**Comment by destlaver** [comment]
I tried at last 3 different methods before giving up. It would be great if you can avoid pytorch3d

**Comment by kotaxyz** [comment]
i have the same issue ,have you been able to get over it

> I tried at last 3 different methods before giving up. It would be great if you can avoid pytorch3d
