### ISSUE TITLE
Custom SD-based models

### ISSUE THREAD

**Issue by ReRadioActivity** [KU-CVLAB/3DFuse#7]
Is it possible to use any other custom SD-based model with this repo and get a decent result? Or only the ones that are presented in the Gradio demo work properly?

**Comment by j0seo** [comment]
We used SD v1.5 in our framework. It's difficult to answer whether other custom SDs can be used since we haven't tried them. However, if the sparse depth injector is newly trained with custom SDs, we expect that it will also perform well.

**Comment by ReRadioActivity** [comment]
Thank you for your reply. Although, now, I have a few questions about the sparse depth injector (going to call it SDI for short):
1. Is ANY 3D data required for the training of SDI? I think the papers says that it doesn't, but I just want to be sure.
2. Is code for training the SDI available in your repo? If yes, then can you tell me in what directory?
3. How much time and computational power does it require to train it?
Hope, that the questions are not too bothersome.
